config/routes.rb
Rails.application.routes.draw do

#this section to deal with routing pages

root 'listings#index'

#payment routes
get 'reservations/:id/paypal' => 'reservations#paypal', as: 'paypal_form'
post 'reservations/:id/paypal_checkout' => 'reservations#paypal_checkout', as: 'paypal_checkout'



# This section is also used to deal with user creation/logging in
# This is clearance authentication

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/users/:id/listings" => "users#listings", as: "user_listings"


# end of clearance authecation
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

# superadmin routes
  get "/users/:id/super_admin" => "users#super_admin", as: "super_admin"

  get "/listings/:id/approve" => "listings#approval", as: "approve"



#routes for listing
 
resources :listings
resources :reservations, only: [:new, :index, :create, :destroy]


get "/users/:id/reservations" => "users#reservations", as: "user_reservations"

#end
  
  
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	has_many :reservations, dependent: :destroy
	mount_uploaders :listing_images, ListingImagesUploader
	validates :capacity, numericality: { greater_than: 0 }
	validates :price, numericality: { greater_than: 0 }
	validates :address, :city, :country, :zipcode, :accomodation_type, :place_type, :listing_name, :description, :presence => true

	filterrific(
	  default_filter_params: { sorted_by: 'created_at_desc' },
	  available_filters: [
	    :sorted_by,
	    :search_query,
	    :with_country_id,
	    :with_created_at_gte
	  ]
	)

	def self.search(search)
	  search.downcase!
	  Listing.where("lower(city) LIKE ? OR lower(listing_name) LIKE ?", "%#{search}%", "%#{search}%")
	end

	def self.search_with_date(search, start_date, end_date)
		search.downcase!
	  	Listing.joins(:reservations)
	  		.where("lower(city) LIKE ? OR lower(listing_name) LIKE ?", "%#{search}%", "%#{search}%")
	  		.where.not("reservations.start_date < ? AND ? <= reservations.end_date", start_date, start_date)
	  		.where.not("reservations.start_date <= ? AND ? < reservations.end_date", end_date, end_date)

	  	# {listing1, listing2}.reservation
	  	# listing.reservation
	  	# Listing.joins(:reservations).where('reservations.start_date ?')

	  	# output.map do |lsting|
	  	# 	lsting.reservations
	  	# 		.where.not("start_date < ? AND ? <= end_date", start_date, start_date)
	  	# 		.where.not("start_date <= ? AND ? < end_date", end_date, end_date)
	  	# 		.map { |x| x.listing }
	  	# end
	  	# Relation{listing1,listing2,...}
	  	# [Relations1{listing1, listing2,}, Relations2, ...]
	  	# [[listing, listing, ...], [listing]]
	  	# [listing, listing]
	  	# byebug

	  	#output.select {|x| x.reservation_check(start_date, end_date)}
	end

	# def reservation_check(start_date, end_date)

	# 	@dates = Reservation.all.where(listing_id: self.id).where(payment_status: true)
	# 	@start_date = Date.parse(start_date)
	# 	@end_date = Date.parse(end_date)
		
 #        @dates.detect do |t|
 # 			(t.start_date < @start_date  && @start_date <= t.end_date) && (t.start_date <= @end_date && @end_date < t.end_date) 
 #        end.nil?
	# end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	def index
		if params[:search] && params[:start_date] && params[:end_date]
    		@listing = Listing.search_with_date(params[:search], params[:start_date], params[:end_date]).where(approval_status: true).order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
    	elsif params[:search]
    		@listing = Listing.search(params[:search]).where(approval_status: true).order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  		else  
			@listing = Listing.order("created_at DESC").where(approval_status: true).paginate(:page => params[:page], :per_page => 8)
		end
	end

	def new 
		@listing = Listing.new
		render template: "listings/new"
	end

	def create
		@listing = current_user.listings.new(listing_params)
		if @listing.save && @listing.valid?
			redirect_to "/listings"
		else
			render template: "listings/new"
		end
	end

	def show
		current_listing
		@reservation = @listing.reservations.new
	end

	def edit
		current_listing
	end

	def update
		current_listing
		if @listing.update(listing_params)
  		end
  			redirect_to "/listings/#{@listing.id}/edit"
	end

	def destroy
		current_listing.destroy
	end

	def approval
		if current_user.customer?
	        flash[:notice] = "Sorry. You are not allowed to perform this action."
	        return redirect_to current_user, notice: "Sorry. You do not have the permissino to verify a property."
      	else
      		current_listing
      		@listing.approval_status = true
      		@listing.save
      		redirect_to super_admin_path(current_user)
      		flash[:success] = "Listing have been approved."
      	end
	end

	private 
	def current_listing
		@listing = Listing.find(params[:id])
	end

	def listing_params
		params.require(:listing).permit(:accomodation_type, :capacity, :description, :listing_name, :address, :city, :country, :zipcode, :price, :place_type, {listing_images: []})
	end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing do |listing|%>
	<div class="form-group">
		<%= listing.label :listing_name %>
		<%= listing.text_field :listing_name, type: 'text', class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= listing.label :listing_images %>
		<%= listing.file_field :listing_images, multiple: true %>
	</div>
		
	<div class="form-group">
		<%= listing.label :place_type  %> <br>
		<%= listing.radio_button :place_type, "shared_room", class: "form-check form-check-inline" %>
		<%= listing.label :place_type_shared_room, "Shared Room", class:'form-check-label' %>
		<%= listing.radio_button :place_type, "private_room", class: "form-check form-check-inline" %>
		<%= listing.label :place_type_private_room, "Private Room" , class:'form-check-label' %>
		<%= listing.radio_button :place_type, "entire_home", class: "form-check form-check-inline" %>
		<%= listing.label :place_type_entire_home, "Entire Home/Aparment" , class:'form-check-label' %>
	</div>


	<div class="form-group">
	  <%= listing.label :price  %>
	  <%= listing.text_field :price, type: "integer", class: 'form-control' %>
		<%= @listing.errors[:price][0] %>
	</div>
	
	<div class="form-group">
	  <%= listing.label :address  %>
	  <%= listing.text_field :address, type: "text", class: 'form-control' %>
	</div>
	
	<div class = "row">	
		<div class ="col-md-4">
			<div class="form-group">
				<%= listing.label :city  %>
				<%= listing.text_field :city, type: "text", class: 'form-control' %>
			</div>
		</div>
		
		<div class ="col-md-4">
			<div class="form-group">
				<%= listing.label :country %>
				<%= listing.text_field :country, type: "text", class: 'form-control' %>
			</div>
		</div>

		<div class ="col-md-4">
			<div class="form-group">
				<%= listing.label :zipcode %>
				<%= listing.text_field :zipcode, type: "text", class: 'form-control' %>
			</div>
		</div>
	</div>


	<div class="form-group">
	  <%= listing.label :capacity %>
	  <%= listing.text_field :capacity, type: "integer", class: 'form-control' %>
	</div>

	

	<div class="form-group">
	  <%= listing.label :accomodation_type %>
	  <%= listing.text_field :accomodation_type, type: "integer", class: 'form-control' %>
	</div>

	<div class="form-group">
	  <%= listing.label :description %>
	  <%= listing.text_field :description, type: 'text', class: 'form-control' %>
	</div>

	<p><%= listing.submit 'Submit', :class => 'btn btn-primary' %> </p>
<% end %>

app/views/listings/edit.html.erb
<div class = "container">
	<% if @listing.listing_images.length == 0 %>
		<h1>There are currently no images</h1>
	<% else %>
		<%= image_tag @listing.listing_images[0].thumb %>
	<% end %>
	<%= render 'form' %>
	<%= link_to "View Listing", listing_path(@listing), class: "btn btn-primary" %>
</div>

app/views/listings/index.html.erb
<div class = container>
	<div class="page-header">
		<h2>Homes</h2>
	</div>
	<% if @listing.present? %>
		<% @listing.each_slice(4) do |x| %>
			<div class = 'row'>
			<% x.each do |y| %> 
				<div class = "col-xs-6 col-md-3">
					<% if y.listing_images.length == 0 %>
						<div class = "thumbnail">
							<%= link_to image_tag("/assets/no-image-box.png"), listing_path(y) %>
							<div class="caption">
			        			<h3><%= y.listing_name%></h3>
			        			<p><%= y.description%></p>
			        		</div>
		        		</div>
					<% else %>
						<div class = "thumbnail">
							<%= link_to image_tag(y.listing_images[0]), listing_path(y) %>
							<div class="caption">
			        			<h3><%= y.listing_name%></h3>
			        			<p><%= y.description%></p>
			        		</div>
			        	</div>
					<% end %>		
				</div>
		  	<% end %>
			</div>
		<%end%>
		<%= will_paginate @listing %>
	<% else %>
  		<p>There are no listings containing the term(s) <%= params[:search] %>.</p>
	<% end %>


</div>

app/views/listings/new.html.erb
<div class = 'container'>
	<div class="page-header">
		<h2>New Home</h2>
	</div>
	
	<%= render 'form'%>
</div>

app/views/listings/show.html.erb
<div class="jumbotron">
    <% image = @listing.listing_images%>
    <% if image[0] == nil %>
      <%= image_tag("/assets/no-image-box.png", :class => "jumbo-img") %>
    <% else %>
      <%= image_tag image[0].jumbo, :class => "jumbo-img"%>
    <% end %>
</div>

<div class="container">
  <div class= "subcontainer-1">
    <div class = "sub-box-line">
      <div class= "row" id="listing_controls">
        <div class="col-md-4">
          <a class= "preview-all-listing"> View Photos</a>
        </div>

        <% if signed_in? %>
          <div class="col-md-3">
            <% if !current_user.customer? && @listing.approval_status == false %>
              <%= link_to "Approve", approve_path(params[:id]), :class => "waterbnb_button"%>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
    
    <div class = "sub-box-line">
      <h1><%=@listing.description%></h1>
    
      <div class = "row" >
        <div class="col-md-9">
          <p><%= @listing.accomodation_type %> . <%= @listing.city %></p>
          <p>Hosted by <%= @listing.user.first_name %></p>
          <p><span class="glyphicon glyphicon-user" aria-hidden="true"></span><%=@listing.capacity%> guests</p>
        </div>

        <div class="col-md-3">
          <div class="profile-icon">
            <% profile_img = @listing.user.profile %>
            <% if profile_img.nil? %> 
              <%= image_tag("/assets/no-image-box.png")%>
            <% else %>
              <%= image_tag profile_img.profile_icon, :class => "profile-icon-image"%>
            <% end %>
          </div>
        </div>
      </div>
          <p><%=@listing.description%></p>  
    </div>

    <div class = "sub-box-line">
      <h2>Prices</h2>
      <p>Cost of room per night:  $<%= @listing.price %></p>
    </div>

    <div class = "carousel-box">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
      <!--   <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol> -->

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <% number = 0 %>
          <% @listing.listing_images.each do |t|%>
            <% if number == 0%>
              <div class="item active">
                <%= image_tag t.thumb %>
              </div>
              <% number += 1%>
            <% else %>
              <div class="item">
                <%= image_tag t.thumb %>
              </div>
            <% end %>
          <% end %>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>

  <div class = "subcontainer-2">
    <div class = "subcontainer-2-box">
      <h3 id = "subcontainer-2-header">USD $<%= @listing.price%> per night</h3>
      <div class = "sub-box-line"></div>
      <%= render "reservations/form" %>
      <h3><%= @error %></h3>
    </div>
  </div>
</div>

<%= @listing.place_type %>
  <%= @listing.address %>
  <%= @listing.city %>
  <%= @listing.country %>
  <%= @listing.zipcode %>
  <%= @listing.price %>