config/routes.rb
Rails.application.routes.draw do

#this section to deal with routing pages

root 'listings#index'

#payment routes
get 'reservations/:id/paypal' => 'reservations#paypal', as: 'paypal_form'
post 'reservations/:id/paypal_checkout' => 'reservations#paypal_checkout', as: 'paypal_checkout'



# This section is also used to deal with user creation/logging in
# This is clearance authentication

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/users/:id/listings" => "users#listings", as: "user_listings"


# end of clearance authecation
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

# superadmin routes
  get "/users/:id/super_admin" => "users#super_admin", as: "super_admin"

  get "/listings/:id/approve" => "listings#approval", as: "approve"



#routes for listing
 
resources :listings
resources :reservations, only: [:new, :index, :create, :destroy]


get "/users/:id/reservations" => "users#reservations", as: "user_reservations"

#end
  
  
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [ :customer, :moderator, :superadmin]
  mount_uploader :profile, ProfileUploader
  include Clearance::User
   has_many :authentications, dependent: :destroy
   has_many :listings, dependent: :destroy
   has_many :reservations, dependent: :destroy
    def self.create_with_auth_and_hash(authentication, auth_hash)
      user = self.create!(
        first_name: auth_hash["info"]["first_name"],
        last_name: auth_hash["info"]["last_name"], 
        email: auth_hash["extra"]["raw_info"]["email"],
        password: SecureRandom.hex(10)
      )
      user.authentications << authentication
      return user
    end

    # grab fb_token to access Facebook for user data
    def fb_token
      x = self.authentications.find_by(provider: 'facebook')
      return x.token unless x.nil?
    end
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
  
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end



  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    "/"
  end


  def user_from_params
    first_name = user_params.delete(:first_name)
    last_name = user_params.delete(:last_name)
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.first_name = first_name
      user.last_name = last_name
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		
		# @user.last_name  = params[:user][:last_name]
		# @user.first_name = params[:user][:first_name]
		# @user.email      = params[:user][:email]
		@user = User.find(params[:id])
		if @user.update(user_params)

			redirect_to @user #redirect_to user object will automatically goes to the user_path of that object
		else
			redirect_to edit_user_path
		end

	end


	def listings
		@user = User.find(params[:id])
		@listings = @user.listings
	end

	def super_admin
		@listing = Listing.order("created_at DESC").where(approval_status: false).paginate(:page => params[:page], :per_page => 8)
	end

	def reservations
		@reservation = Reservation.where(user_id: current_user).where(payment_status: true)
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :profile)
	end
end

app/views/users/_form.html.erb
<div class="text_field">
  <%= form.label :first_name %>
  <%= form.text_field :first_name, type: "text" %>
</div>

<div class="text_field">
  <%= form.label :last_name %>
  <%= form.text_field :last_name, type: "text" %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/_user_nav.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><%= link_to 'Profile', user_path(current_user.id) %></li>
  <li role="presentation"><%= link_to 'Listings', user_listings_path(current_user.id) %></li>
  <li role="presentation"><%= link_to 'Reservations', user_reservations_path(current_user.id) %></li>
</ul>

app/views/users/edit.html.erb
	<%= form_for @user do |form| %>
		 <div class="text_field">

		 	<%= image_tag(@user.profile) if @user.profile? %>
			<p><%= form.label :profile %>
			<%= form.file_field :profile %></p>	
			<%= form.hidden_field :profile_cache %>
		</div>

	    <div class="text_field">
			<%= form.label :first_name %>
			<%= form.text_field :first_name, type: "text" %>
		</div>

		<div class="text_field">
			<%= form.label :last_name %>
			<%= form.text_field :last_name, type: "text" %>
		</div>

		<div class="text-field">
			<%= form.label :email %>
			<%= form.text_field :email, type: 'email' %>
		</div>

	    <div class="submit-field">
	      <%= form.submit %>
	    </div>

	    <div class="other-links">
	      <%= link_to t(".sign_in"), sign_in_path %>
	    </div>
	<% end %>

app/views/users/listings.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" ><%= link_to 'Profile', user_path(current_user.id) %></li>
  <li role="presentation" class="active"><%= link_to 'Listings', user_listings_path(current_user.id) %></li>
  <li role="presentation"><%= link_to 'Reservations', user_reservations_path(current_user.id) %></li>
</ul>

<div class="container">
	<% if signed_in? %>

		<div class="page-header">
			<h2>Your Listings</h2>
		</div>

		<% @listings.each_slice(4) do |x| %>
			<div class = 'row'>
				<% x.each do |y| %>
					<div class = "col-xs-6 col-md-3">
						<div class = "thumbnail">
							<% if y.listing_images.length == 0 %>
								<%= link_to image_tag("/assets/no-image-box.png"), listing_path(y) %>
							<% else %>
								<%= link_to image_tag(y.listing_images[0]), listing_path(y) %>	
							<% end %>	
							<div class="caption">
			        			<h3><%= y.listing_name%></h3>
			        			<p><%= y.description%></p>
			        			<% if y.user_id == current_user.id %>
									<p><%= link_to "edit listings", edit_listing_path(y), :class => "btn btn-primary"%></p>
								<% end %>
			        		</div>	
						</div>
					</div>
				<% end %>
			</div>
		<%end%>

	<% end %>
</div>

        

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
  <%= link_to "Sign up with Facebook", "/auth/facebook" %>
</div>

app/views/users/reservations.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to 'Profile', user_path(current_user.id) %></li>
  <li role="presentation"><%= link_to 'Listings', user_listings_path(current_user.id) %></li>
  <li role="presentation" class="active"><%= link_to 'Reservations', user_reservations_path(current_user.id) %></li>
</ul>

<div class = "container">
	<% if @reservation.present? %>
		<% past_reservation = @reservation.where("? >= end_date", Time.now ) %>
		<% current_reservation = @reservation.where("end_date > ?", Time.now) %>
		<div class="page-header">
  			<h2>Upcoming Reservations</h1>
		</div>
		<% if current_reservation.present? %>
			<% current_reservation.each_slice(4) do |x| %>
				<div class = 'row'>
					<% x.each do |y| %>
					<% z = y.listing%>
						<div class = "col-xs-6 col-md-3">
							<div class = "thumbnail">
								<% if z.listing_images.length == 0 %>
									<%= link_to image_tag("/assets/no-image-box.png"), listing_path(z) %>
					        		
								<% else %>
									<%= link_to image_tag(z.listing_images[0]), listing_path(z) %>
						        	
								<% end %>	
								<div class="caption">
				        			<h3><%= z.listing_name%></h3>
				        			<h4>Start Date <%= y.start_date %></h4>
				        			<h4>End Date <%= y.end_date %></h4>
				        			<h4>Duration <%= (y.end_date - y.start_date).to_i %> days</h4>
				        			<p><%= z.description%></p>
				        		</div>	
		        			</div>
						</div>
				  	<% end %>
				</div>
			<%end%>
		<% end %> 
		<div class="page-header">
  			<h2>Past Reservations</h1>
		</div>
		<% if past_reservation.present? %>
			<% past_reservation.each_slice(4) do |x| %>
				<div class = 'row'>
					<% x.each do |y| %>
					<% z = y.listing%>
						<div class = "col-xs-6 col-md-3">
							<div class = "thumbnail">
								<% if z.listing_images.length == 0 %>
									<%= link_to image_tag("/assets/no-image-box.png"), listing_path(z) %>
					        		
								<% else %>
									<%= link_to image_tag(z.listing_images[0]), listing_path(z) %>
						        	
								<% end %>	
								<div class="caption">
				        			<h3><%= z.listing_name%></h3>
				        			<h4>Start Date <%= y.start_date %></h4>
				        			<h4>End Date <%= y.end_date %></h4>
				        			<h4>Duration <%= (y.end_date - y.start_date).to_i %> days</h4>
				        			<p><%= z.description%></p>
				        		</div>	
		        			</div>
						</div>
				  	<% end %>
				</div>
			<%end%>
		<% end %> 
	<% else %>
			<p>You have not made any reservations.</p>
	<% end %>
</div>

app/views/users/show.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><%= link_to 'Profile', user_path(current_user.id) %></li>
  <li role="presentation"><%= link_to 'Listings', user_listings_path(current_user.id) %></li>
  <li role="presentation"><%= link_to 'Reservations', user_reservations_path(current_user.id) %></li>
</ul>


<% if flash[:success] || flash[:error]%>
	<div class="alert alert-success">
		<% flash.each do |key, value| %>
	      <div class="<%= flash_class(key) %>">
	            <%= value %>
	      </div>
		<% end %>
	</div>
<% end %>
<div class= "container">
	<div class="page-header">
		<h2>Profile</h1>
	</div>

	<p><%= "Name:     " + @user.first_name + @user.last_name %></p>	
	<p><%= "Email :   " + @user.email %></p>
	<%= link_to "Edit Profile", edit_user_path(current_user) %> 
</div>

app/views/users/super_admin.html.erb
<% if flash[:success] %>
	<div class="alert alert-success">
        <%= flash[:success]%>
	</div>
<% end %>

<div class = container>
	<div class="page-header">
		<h2>Homes</h2>
	</div>

	<% @listing.each_slice(4) do |x| %>
		<div class = 'row'>
		<% x.each do |y| %> 
			<div class = "col-xs-6 col-md-3">
				<% if y.listing_images.length == 0 %>
					<div class = "thumbnail">
						<%= link_to image_tag("/assets/no-image-box.png"), listing_path(y) %>
						<div class="caption">
		        			<h3><%= y.listing_name%></h3>
		        			<p><%= y.description%></p>
		        		</div>
	        		</div>
				<% else %>
					<div class = "thumbnail">
						<%= link_to image_tag(y.listing_images[0]), listing_path(y) %>
						<div class="caption">
		        			<h3><%= y.listing_name%></h3>
		        			<p><%= y.description%></p>
		        		</div>
		        	</div>
				<% end %>		
			</div>
	  	<% end %>
		</div>
	<%end%>


	<%= will_paginate @listing %>
</div>