config/routes.rb
Rails.application.routes.draw do

#this section to deal with routing pages

root 'listings#index'

#payment routes
get 'reservations/:id/paypal' => 'reservations#paypal', as: 'paypal_form'
post 'reservations/:id/paypal_checkout' => 'reservations#paypal_checkout', as: 'paypal_checkout'



# This section is also used to deal with user creation/logging in
# This is clearance authentication

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/users/:id/listings" => "users#listings", as: "user_listings"


# end of clearance authecation
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

# superadmin routes
  get "/users/:id/super_admin" => "users#super_admin", as: "super_admin"

  get "/listings/:id/approve" => "listings#approval", as: "approve"



#routes for listing
 
resources :listings
resources :reservations, only: [:new, :index, :create, :destroy]


get "/users/:id/reservations" => "users#reservations", as: "user_reservations"

#end
  
  
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController

end

app/helpers/payment_helper.rb
module PaymentHelper

end

app/views/payment/index.html.erb
<%= link_to "Make Payment Through Paypal", payment_braintree_path %>

app/views/payment/paypal_form.html.erb
<div class="demo-frame">
  <%= form_for :checkout_form, url: paypal_checkout_path, html: { id: "cardForm"} do |form| %>

  <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
  <div id="card-number" class="hosted-field"></div>

  <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
  <div id="expiration-date" class="hosted-field"></div>

  <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
  <div id="cvv" class="hosted-field"></div>

  <%= form.hidden_field "payment_method_nonce" %>
  <% reservation = Reservation.find(params[:id])%>
  <%= form.hidden_field :ammount, value: "#{reservation.listing.price}" %>
  <%= form.hidden_field :reservation, value: '#{reservation}'

  <div class="button-container">
  <%= form.submit "Purchase", disabled: false, class: "btn btn-primary", id: "submit-payment-btn" %>
  </div>
  <% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>