config/routes.rb
Rails.application.routes.draw do

#this section to deal with routing pages

root 'listings#index'

#payment routes
get 'reservations/:id/paypal' => 'reservations#paypal', as: 'paypal_form'
post 'reservations/:id/paypal_checkout' => 'reservations#paypal_checkout', as: 'paypal_checkout'



# This section is also used to deal with user creation/logging in
# This is clearance authentication

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/users/:id/listings" => "users#listings", as: "user_listings"


# end of clearance authecation
 get "/auth/:provider/callback" => "sessions#create_from_omniauth"

# superadmin routes
  get "/users/:id/super_admin" => "users#super_admin", as: "super_admin"

  get "/listings/:id/approve" => "listings#approval", as: "approve"



#routes for listing
 
resources :listings
resources :reservations, only: [:new, :index, :create, :destroy]


get "/users/:id/reservations" => "users#reservations", as: "user_reservations"

#end
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waterbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	
    
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="navbar-brand"><%= link_to "Waterbnb", root_path %></p>
    </div>

      
    <%= form_tag(listings_path, :method => "get", class: "navbar-form navbar-left") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= date_field_tag :start_date, params[:start_date], class:"form-control" %>
    </div>
    <div class="form-group">
      <%= date_field_tag :end_date, params[:end_date], value: "End Date", class:"form-control"%>
    </div>
    <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li><%= link_to "Add Listings", new_listing_path %></li>
        <li class="dropdown"> 
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a><%= link_to "Your Listings", user_listings_path(current_user) %></a></li>
              <li><a><%= link_to "Your profile", user_path(current_user) %></a></li>
              <li><a><%= link_to "Your Reservations", user_reservations_path(current_user) %></a></li>
              <% if current_user.superadmin?%>
                <li><a><%= link_to "Unapproved Listings", super_admin_path(current_user) %></a></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <li><a><%= link_to "Sign out", sign_out_path, method: :delete %></a></li>
            </ul>
          <% else %>
              <li><%= link_to "Sign in", sign_in_path %></li>
              <li><%= link_to "Sign up", sign_up_path %></li>
          <% end %>  
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


    <%= yield %>
  </body>
</html>